### PR TITLE
updata zh_cn.json

### PR DESCRIPTION
**Pull request by seaseii**

### CODE REVIEW

**Comment by seaseii** [comment]
Hi,I'm glad to see the 0.6 update.But I have a question。Why eat melted cinder flour's hazelnut will give player blindness rather than  potent speed?Is this a joke?

**Comment by seaseii** [comment]
> I'll take a look at the respective classes when I can, as this is not intentional. What loader are you using? (Fabric or Forge)

Oh,It's Fabric

**Comment by DakotaPride** [comment]
Try reinstalling the file, as it should be fixed now. Thank you for bringing this to my attention. However, next time there is an issue like this, please create an issue report specifying the MC version, Loader version, or any other helpful information regarding the error. Apologies for the inconvenience!

**Comment by seaseii** [comment]
> Try reinstalling the file, as it should be fixed now. Thank you for bringing this to my attention. However, next time there is an issue like this, please create an issue report specifying the MC version, Loader version, or any other helpful information regarding the error. Apologies for the inconvenience!

Just casually, it turns out this is really a mistake: )

**Comment by DakotaPride** [comment]
Apologies, but could you update the new additions to the file when you get a chance? I understand if not, and have a wonderful day/night! (any branch is fine if you do decide to update it)

**Comment by seaseii** [comment]
> Apologies, but could you update the new additions to the file when you get a chance? I understand if not, and have a wonderful day/night! (any branch is fine if you do decide to update it)

I apologize for only seeing the message.
I will complete this matter as soon as possible
sry

**Pull request merged**
