### PR TITLE
Add lang/ru_ru.json

### PR DESCRIPTION
**Pull request by Negodya1**
Russian translation I made for my mod pack

### CODE REVIEW

**Review by DakotaPride — CHANGES_REQUESTED** [review]
Thank you for localizing this mod for ru_ru! However, there are some missing translations present (such as advancements added in v1.3 or the translations for the Enchantment Descriptions integration)

Could you first add these translations?

**Review by DakotaPride — COMMENTED** [review]
(addon to the previous comment)

It also looks like most other v1.3 translations aren't provided. I understand that v1.3 is not currently released, but would be appreciated to add as this version of the mod will be released sometime soon.

**Comment by Negodya1** [comment]
No problem. I will translate it in a few hours

**Comment by Negodya1** [comment]
It's done.

You also have wrong string (283) in en_us file
Снимок

**Review by DakotaPride — APPROVED** [review]

**Comment by DakotaPride** [comment]
Currently waiting for Github to allow me to merge, apologies for the wait!
image

**Review by DakotaPride — APPROVED** [review]

**Pull request merged**
